{
    "swagger": "2.0",
    "info": {
        "title": "DirectoryRoles"
    },
    "paths": {
        "/directoryRoles": {
            "get": {
                "parameters": [
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK. Indicates success. The results are returned in the response body.",
                        "examples": {
                            "application/json": {
                                "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/Microsoft.DirectoryServices.DirectoryRole",
                                "value": [
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                        "objectType": "Role",
                                        "objectId": "02618ff0-e643-450d-b9b2-2f812364eb2c",
                                        "deletionTimestamp": null,
                                        "description": "Helpdesk Administrator has access to perform common helpdesk related tasks.",
                                        "displayName": "Helpdesk Administrator",
                                        "isSystem": true,
                                        "roleDisabled": false,
                                        "roleTemplateId": "729827e3-9c14-49f7-bb1b-9608f156bbb8"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                        "objectType": "Role",
                                        "objectId": "044ca859-dc72-47cb-b466-7f6e78398979",
                                        "deletionTimestamp": null,
                                        "description": "Allows access read tasks and a subset of write tasks in the directory.",
                                        "displayName": "Directory Writers",
                                        "isSystem": true,
                                        "roleDisabled": false,
                                        "roleTemplateId": "9360feb5-f418-4baa-8175-e2a00bac4301"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                        "objectType": "Role",
                                        "objectId": "44261f4c-b686-44c1-8997-310171ed4ca8",
                                        "deletionTimestamp": null,
                                        "description": "Allows access to various read only tasks in the directory. ",
                                        "displayName": "Directory Readers",
                                        "isSystem": true,
                                        "roleDisabled": false,
                                        "roleTemplateId": "88d8e3e3-8f55-4a1e-953a-9b9898b8876b"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                        "objectType": "Role",
                                        "objectId": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8",
                                        "deletionTimestamp": null,
                                        "description": "Company Administrator role has full access to perform any operation in the company scope.",
                                        "displayName": "Company Administrator",
                                        "isSystem": true,
                                        "roleDisabled": false,
                                        "roleTemplateId": "62e90394-69f5-4237-9190-012177145e10"
                                    }
                                ]
                            }
                        }

                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Read</i></b> or <b><i>Contacts.Write</i></b></p>",
                "summary": "You can get a collection of directory roles from your tenant.",
                "operationId": "get directory roles"
            },
            "post": {
                "parameters": [
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    },
                    {
                        "in": "body",
                        "description": "The request body, not a real parameter",
                        "name": "bodyparam",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/directoryRole",
                            "example": {
                                "roleTemplateId": "88d8e3e3-8f55-4a1e-953a-9b9898b8876b"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created. Indicates success. The newly activated directory role is returned in the response body.",
                        "examples": {
                            "application/json": {
                                "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/Microsoft.DirectoryServices.DirectoryRole/@Element",
                                "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                "objectType": "Role",
                                "objectId": "ebabdd59-04ba-46f0-bd7f-bef08fe8fa9b",
                                "deletionTimestamp": null,
                                "description": "Allows access to various read only tasks in the directory. ",
                                "displayName": "Directory Readers",
                                "isSystem": true,
                                "roleDisabled": false,
                                "roleTemplateId": "88d8e3e3-8f55-4a1e-953a-9b9898b8876b"
                            }
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Directory.Write</i></b></p>",
                "summary": "Activate a directory role in the tenant.",
                "operationId": "activate directory role"
            }
        },
        "/directoryRoleTemplates": {
            "get": {
                "parameters": [
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK. Indicates success. The results are returned in the response body.",
                        "examples": {
                            "application/json": {
                                "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                "value": [
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "729827e3-9c14-49f7-bb1b-9608f156bbb8",
                                        "deletionTimestamp": null,
                                        "description": "Helpdesk Administrator has access to perform common helpdesk related tasks.",
                                        "displayName": "Helpdesk Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "f023fd81-a637-4b56-95fd-791ac0226033",
                                        "deletionTimestamp": null,
                                        "description": "Service Support Administrator has access to perform common support tasks.",
                                        "displayName": "Service Support Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "b0f54661-2d74-4c50-afa3-1ec803f12efe",
                                        "deletionTimestamp": null,
                                        "description": "Billing Administrator has access to perform common billing related tasks.",
                                        "displayName": "Billing Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "b5468a13-3945-4a40-b0b1-5d78c2676bbf",
                                        "deletionTimestamp": null,
                                        "description": "Allows access and management of users mailboxes.",
                                        "displayName": "Mailbox Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "4ba39ca4-527c-499a-b93d-d9b492c50246",
                                        "deletionTimestamp": null,
                                        "description": "Allows ability to perform tier1 support tasks.",
                                        "displayName": "Partner Tier1 Support"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "e00e864a-17c5-4a4b-9c06-f5b95a8d5bd8",
                                        "deletionTimestamp": null,
                                        "description": "Allows ability to perform tier2 support tasks.",
                                        "displayName": "Partner Tier2 Support"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "88d8e3e3-8f55-4a1e-953a-9b9898b8876b",
                                        "deletionTimestamp": null,
                                        "description": "Allows access to various read only tasks in the directory. ",
                                        "displayName": "Directory Readers"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "29232cdf-9323-42fd-ade2-1d097af3e4de",
                                        "deletionTimestamp": null,
                                        "description": "Exchange Service Administrator.",
                                        "displayName": "Exchange Service Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "75941009-915a-4869-abe7-691bff18279e",
                                        "deletionTimestamp": null,
                                        "description": "Lync Service Administrator.",
                                        "displayName": "Lync Service Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "fe930be7-5e62-47db-91af-98c3a49a38b1",
                                        "deletionTimestamp": null,
                                        "description": "User Account Administrator has access to perform common user management related tasks.",
                                        "displayName": "User Account Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "9360feb5-f418-4baa-8175-e2a00bac4301",
                                        "deletionTimestamp": null,
                                        "description": "Allows access read tasks and a subset of write tasks in the directory.",
                                        "displayName": "Directory Writers"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "62e90394-69f5-4237-9190-012177145e10",
                                        "deletionTimestamp": null,
                                        "description": "Company Administrator role has full access to perform any operation in the company scope.",
                                        "displayName": "Company Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "a0b1b346-4d3e-4e8b-98f8-753987be4970",
                                        "deletionTimestamp": null,
                                        "description": "Every user is implicitly considered to be a member of the User Role.",
                                        "displayName": "User"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "d65e02d2-0214-4674-8e5d-766fb330e2c0",
                                        "deletionTimestamp": null,
                                        "description": "Allows creation of new email verified users.",
                                        "displayName": "Email Verified User Creator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "eb1d8c34-acf5-460d-8424-c1f1a6fbdb85",
                                        "deletionTimestamp": null,
                                        "description": "Allows access manage AdHoc license.",
                                        "displayName": "AdHoc License Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "f28a1f50-f6e7-4571-818b-6a12f2af6b6c",
                                        "deletionTimestamp": null,
                                        "description": "SharePoint Service Administrator.",
                                        "displayName": "SharePoint Service Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "d405c6df-0af8-4e3b-95e4-4d06e542189e",
                                        "deletionTimestamp": null,
                                        "description": "Device Users",
                                        "displayName": "Device Users"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "9f06204d-73c1-4d4c-880a-6edb90606fd8",
                                        "deletionTimestamp": null,
                                        "description": "Device Administrators",
                                        "displayName": "Device Administrators"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "9c094953-4995-41c8-84c8-3ebb9b32c93f",
                                        "deletionTimestamp": null,
                                        "description": "Device Join",
                                        "displayName": "Device Join"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "c34f683f-4d5a-4403-affd-6615e00e3a7f",
                                        "deletionTimestamp": null,
                                        "description": "Workplace Device Join",
                                        "displayName": "Workplace Device Join"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "17315797-102d-40b4-93e0-432062caca18",
                                        "deletionTimestamp": null,
                                        "description": "Compliance administrator.",
                                        "displayName": "Compliance Administrator"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "d29b2b05-8046-44ba-8758-1e26182fcf32",
                                        "deletionTimestamp": null,
                                        "description": "Directory Synchronization Accounts",
                                        "displayName": "Directory Synchronization Accounts"
                                    },
                                    {
                                        "odata.type": "Microsoft.DirectoryServices.DirectoryRoleTemplate",
                                        "objectType": "RoleTemplate",
                                        "objectId": "2b499bcd-da44-4968-8aec-78e1674fa64d",
                                        "deletionTimestamp": null,
                                        "description": "Allows access to read and edit device properties. ",
                                        "displayName": "Device Managers"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Read</i></b> or <b><i>Contacts.Write</i></b></p>",
                "summary": "You can get a collection of directory roles from your tenant.",
                "operationId": "get directory role templates"
            }
        },
        "/directoryRoles/{object_id}": {
            "get": {
                "parameters": [
                    {
                        "in": "path",
                        "description": "The object ID (GUID) of the target directory role.",
                        "name": "object_id",
                        "required": true,
                        "type": "string",
                        "default": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8"
                    },
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK. Indicates success. The directory role is returned in the response body.",
                        "examples": {
                            "application/json": {
                                "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/Microsoft.DirectoryServices.DirectoryRole/@Element",
                                "odata.type": "Microsoft.DirectoryServices.DirectoryRole",
                                "objectType": "Role",
                                "objectId": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8",
                                "deletionTimestamp": null,
                                "description": "Company Administrator role has full access to perform any operation in the company scope.",
                                "displayName": "Company Administrator",
                                "isSystem": true,
                                "roleDisabled": false,
                                "roleTemplateId": "62e90394-69f5-4237-9190-012177145e10"
                            }
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Read</i></b> or <b><i>Contacts.Write</i></b></p>",
                "summary": "Get a specified directory role.",
                "operationId": "get directory role by id"
            }
        },
        "/directoryRoles/{object_id}/$links/members": {
            "get": {
                "parameters": [
                    {
                        "in": "path",
                        "description": "The object ID (GUID) of the target directory role.",
                        "name": "object_id",
                        "required": true,
                        "type": "string",
                        "default": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8"
                    },
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    }

                ],
                "responses": {
                    "200": {
                        "description": "OK. Indicates success. A collection of links to the directory role members is returned.",
                        "examples": {
                            "application/json": {
                                "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/$links/members",
                                "value": [
                                    {
                                        "url": "https://graph.windows.net/myorganization/directoryObjects/f19096bf-a58c-46ba-9ffd-0344f1daecf8/Microsoft.DirectoryServices.User"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Read</i></b> or <b><i>Contacts.Write</i></b></p>",
                "summary": "Gets the members of the directory role by link.",
                "operationId": "get directory role members links"
            },
            "post": {
                "parameters": [
                    {
                        "in": "path",
                        "description": "The object ID (GUID) of the target directory role.",
                        "name": "object_id",
                        "required": true,
                        "type": "string",
                        "default": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8"
                    },
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    },

                    {
                        "in": "body",
                        "description": "The request body contains one or more links to users or service principals to add to the directory role.",
                        "name": "bodyparam",
                        "required": true,
                        "schema": {
                            "required": [ "url" ],
                            "properties": {
                                "url": {
                                    "type": "string"
                                }
                            },
                            "example": {
                                "url": "https://graph.windows.net/myorganization/directoryObjects/3eb6055a-baeb-44d4-a1ea-2fee86d8891b"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content. Indicates success. No response body is returned.",
                        "examples": {
                            "application/json": "none"
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Write</i></b></p>",
                "summary": "Add members to a directory role.",
                "operationId": "add directory role members"
            }
        },
        "/directoryRoles/{object_id}/$links/members/{member_id}": {
            "delete": {
                "parameters": [
                    {
                        "in": "path",
                        "description": "The object ID (GUID) of the target directory role.",
                        "name": "object_id",
                        "required": true,
                        "type": "string",
                        "default": "cb5d9ae9-6e2c-41a0-9194-0d4aef426ba8"
                    },
                    {
                        "in": "path",
                        "description": "The object ID (GUID) of the member to be removed. Can be a user or a service principal.",
                        "name": "member_id",
                        "required": true,
                        "type": "string",
                        "default": "3eb6055a-baeb-44d4-a1ea-2fee86d8891b"
                    },
                    {
                        "in": "query",
                        "description": "The version of the Graph API to target. Beginning with version 1.5, the api-version string is represented in major.minor format. Prior releases were represented as date strings: '2013-11-08' and '2013-04-05'. Required.",
                        "name": "api-version",
                        "required": true,
                        "type": "string",
                        "default": "1.6"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content. Indicates success. No response body is returned.",
                        "examples": {
                            "application/json": "none"
                        }
                    }
                },
                "description": "<p><i>Required scope</i>: <b><i>Contacts.Write</i></b></p>",
                "summary": "Delete a user or service principal from the directory role.",
                "operationId": "delete directory role member"
            }
        }
    },
    "host": "graph.windows.net",
    "basePath": "/myorganization",
    "schemes": [ "https" ],
    "definitions": {

        "directoryRole": {
            "required": [
                "roleTemplateId"
            ],
            "properties": {
                "objectType": {
                    "type": "string",
                    "readOnly": "true"
                },
                "objectId": {
                    "type": "string",
                    "readOnly": "true"
                },
                "deletionTimestamp": {
                    "type": "date-time",
                    "readOnly": "true"
                },
                "description": {
                    "type": "string",
                    "readOnly": "true"
                },
                "displayName": {
                    "type": "string",
                    "readOnly": "true"
                },
                "isSystem": {
                    "type": "boolean",
                    "readOnly": "true"
                },
                "roleDisabled": {
                    "type": "boolean",
                    "readOnly": "true"
                },
                "roleTemplateId": {
                    "type": "string",
                    "required": "true"
                }
            }
        },
        "directoryRoleTemplate": {
            "properties": {
                "objectType": {
                    "type": "string",
                    "readOnly": "true"
                },
                "objectId": {
                    "type": "string",
                    "readOnly": "true"
                },
                "deletionTimestamp": {
                    "type": "date-time",
                    "readOnly": "true"
                },
                "description": {
                    "type": "string",
                    "readOnly": "true"
                },
                "displayName": {
                    "type": "string",
                    "readOnly": "true"
                }
            }
        }
    }
}
